version: '3'
services:
  mongo:
    container_name: mongo-local
    restart: unless-stopped
    ports:
      - '27018:27017'
    # command: mongod --setParameter authenticationMechanisms=SCRAM-SHA-1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    image: 'mongo:latest'
    healthcheck:
      test: ["CMD", "mongosh","--eval","db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

